### ISSUE TITLE
Create output folder if needed

### ISSUE THREAD

**Issue by christianfds** [christianfds/manga_downloader#1]
If the specified output folder doesn't exists, an error is raised. It should create the folder if needed.

**Comment by RizkiePratama** [comment]
Hi, i make PR to handle these issue. Kindly review the PR and let me know if it suitable enough to be merged https://github.com/christianfds/manga_downloader/pull/3

**Comment by christianfds** [comment]
Sure @RizkiePratama, there is just an small issue with the import order, if you setup the pre-commit hooks locally it ensures it.

**Comment by RizkiePratama** [comment]
@christianfds ah yeah, sorry i didn't check the pre-commit hooks and didn't catch the import order. let me try to fix that
