### ISSUE TITLE
Show list of search result and select by number, instead showing them one by one.

### ISSUE THREAD

**Issue by RizkiePratama** [christianfds/manga_downloader#10]
As current iteration we iterate one by one on all the search result when searching the title.
eg: on my case, it's Pain full to go trough the whole screen to find `Youjo Senki` with the keyword `Youjo Senki` when it actualy take 7 times pressing 'N' to get what i wan't with other different keyword
<img width="1680" alt="Screen Shot 2022-10-11 at 22 58 13" src="https://user-images.githubusercontent.com/5225338/195141654-5c69d48b-0e6d-420b-b9ca-50f69784bd83.png">
<img width="1680" alt="Screen Shot 2022-10-11 at 22 58 51" src="https://user-images.githubusercontent.com/5225338/195141668-5ddab9ac-8227-4bbf-ba62-1c88bdb8ea75.png">

I think it will be convenient to the user to actually have a list of the search result and selecting what they want to download instead of going trough all of that. is this idea still on viable with what you want with this project to be?

**Comment by christianfds** [comment]
That's a good idea, @RizkiePratama.
If you want to work on it i can assign it to you.

I think it would be nice to list it in multiple pages. If we decide to show everything it will way more then needed, if we limit the results the expected one might be left out.
It would be nice to find a lib or write a dynamic method to do this.

**Comment by RizkiePratama** [comment]
Sure, i will work on this issue.

Yep i have the same idea on that, showing it as multiple pages would be neat on longer search result and make it more easier for the user.

**Comment by christianfds** [comment]
Awesome, thank you for helping out!
